# Generated by Django 4.0.6 on 2022-10-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscoreset',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
