# Generated by Django 4.0.6 on 2022-10-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_delete_highscoreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresults',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
