# Generated by Django 4.0.6 on 2022-10-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_userresults_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResults',
        ),
    ]
